Legal requirements
DFE-Digital/conversions-design-history pull request #36
Opened 2022-09-26 13:57 UTC by adyhoran1

Created a design history post about changes to legal requirements content.

2022-09-27 16:45 UTC, mingoland requested changes
Overall it's a good try. Please correct the images and make a `force push` again.

2022-09-27 16:45 UTC, mingoland commented on app/posts/apply-to-become-academy/2022-09-16-legal-requirements.md
> +[![A summary list called Confirm legal requirements. It has four rows: governing body resolution, consultation, diocesan consent and foundation consent.](/images/apply-to-become-academy/legal-require
You changed the link destination only. You forgot to change the image itself.

2022-09-27 16:45 UTC, mingoland commented on app/posts/apply-to-become-academy/2022-09-16-legal-requirements.md
> +[![Has the school provided a governing body resolution? Yes, no, not applicable.](/images/apply-to-become-academy/recording-a-decision/added-a-record-the-decision-link-to-the-projects-list.png)](/ima
Both the image address and the destination are wrong.

2022-09-27 16:45 UTC, mingoland commented on app/posts/apply-to-become-academy/2022-09-16-legal-requirements.md
> +[![A digital task list. A link called legal requirements is highlighted.](/images/apply-to-become-academy/legal-requirements/legal-requirements-task-list.png)](/images/apply-to-become-academy/legal-r
The image looks blurry. It's because the column width is 630px but your image is 532x730, which means it's stretched. 

<img width="663" alt="Screenshot 2022-09-27 at 17 32 45" src="https://user-images.githubusercontent.com/6421298/192586460-52fdf3a8-0137-4124-8fde-e75cacc4ed5d.png">

2022-09-28 10:26 UTC, adyhoran1 commented on app/posts/apply-to-become-academy/2022-09-16-legal-requirements.md
> +[![A digital task list. A link called legal requirements is highlighted.](/images/apply-to-become-academy/legal-requirements/legal-requirements-task-list.png)](/images/apply-to-become-academy/legal-r
I've updated the image so it's 630px wide 🙂

2022-09-28 10:29 UTC, adyhoran1 commented on app/posts/apply-to-become-academy/2022-09-16-legal-requirements.md
> +[![A summary list called Confirm legal requirements. It has four rows: governing body resolution, consultation, diocesan consent and foundation consent.](/images/apply-to-become-academy/legal-require
I've now changed the image 🙂

2022-09-28 10:32 UTC, adyhoran1 commented on app/posts/apply-to-become-academy/2022-09-16-legal-requirements.md
> +[![Has the school provided a governing body resolution? Yes, no, not applicable.](/images/apply-to-become-academy/recording-a-decision/added-a-record-the-decision-link-to-the-projects-list.png)](/ima
I've now updated the image address and destination 🙂

2022-09-28 11:08 UTC, mingoland approved these changes
LGTM. Approved.

2022-09-28 11:09 UTC, merged